-- MySQL Script generated by MySQL Workbench
-- Wed Mar  3 19:23:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema habit_tracker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema habit_tracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `habit_tracker` DEFAULT CHARACTER SET utf8 ;
USE `habit_tracker` ;

-- -----------------------------------------------------
-- Table `habit_tracker`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `habit_tracker`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NULL,
  `phone` VARCHAR(45) NULL,
  `register_with` VARCHAR(45) NOT NULL,
  `email_verified_at` DATETIME NULL,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `salt` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habit_tracker`.`User_meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `habit_tracker`.`User_meta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `ip` VARCHAR(100) NULL,
  `country` VARCHAR(100) NULL,
  `city` VARCHAR(100) NULL,
  `time_zone` VARCHAR(100) NULL,
  `org` VARCHAR(100) NULL,
  `asn` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_meta_User_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_meta_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `habit_tracker`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habit_tracker`.`Habit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `habit_tracker`.`Habit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `date_added` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `regularity` VARCHAR(50) NOT NULL,
  `intensity` ENUM("weak", "normal", "strong") NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Habit_User1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Habit_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `habit_tracker`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habit_tracker`.`Todo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `habit_tracker`.`Todo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `date_added` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `done` TINYINT NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Todo_User1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Todo_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `habit_tracker`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habit_tracker`.`Habit_done`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `habit_tracker`.`Habit_done` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `habit_id` INT NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_User_has_Habit_Habit1_idx` (`habit_id` ASC) VISIBLE,
  INDEX `fk_User_has_Habit_User1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Habit_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `habit_tracker`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Habit_Habit1`
    FOREIGN KEY (`habit_id`)
    REFERENCES `habit_tracker`.`Habit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
